
server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/zq_teamup?characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    url: redis://${REDIS_HOST}:6379
    host: ${REDIS_HOST}
    port: 6379
    ssl: false
    timeout: 5000

jwt:
  secret: ${JWT_SECRET}
  expiration: 604800