wx:
  miniapp:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}
    msgDataFormat: JSON

security:
  jwt:
    secret: ${JWT_SECRET}

spring:
  redis:
    database: 0
    url: redis://${REDIS_HOST}:6379
    host: ${REDIS_HOST}
    port: 6379
    ssl: false
    timeout: 5000

  servlet:
    multipart:
      max-file-size: 5MB  #单个文件最大大小
      max-request-size: 50MB #文件最多上传的大小

aliyun:
  oss:
    accessKeyId: ${ALIYUN_OSS_KEY_ID}
    accessKeySecret: ${ALIYUN_OSS_KEY_SECRET}
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: zq-teamup
  sms:
    accessKeyId: ${ALIYUN_SMS_KEY_ID}
    accessKeySecret: ${ALIYUN_SMS_KEY_SECRET}
    signName: 自强Studio
    templateCode:
      - name: verifyCode
        code: SMS_209826176

sentry:
  traces-sample-rate: 1.0
  send-default-pii: true
