wx:
  miniapp:
    configs:
      - appid: ${WECHAT_APPID}
        secret: ${WECHAT_SECRET}
#        token: #微信小程序消息服务器配置的token
#        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON

security:
  jwt:
    secret: ${JWT_SECRET}