wx:
  miniapp:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}
    msgDataFormat: JSON

security:
  jwt:
    secret: ${JWT_SECRET}

spring:
  redis:
    database: 0
    url: redis://${REDIS_HOST}:6379
    host: ${REDIS_HOST}
    port: 6379
    ssl: false
    timeout: 5000

