---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    group:
      dev:
        - web-dev
        - dao-dev
        - common-dev
      prod:
        - web-prod
        - dao-prod
        - common-prod
