server:
  port: 8080
  tomcat:
    accept-count: 1000
    threads:
      max: 400
      min-spare: 100

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/zq_teamup?characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    url: redis://${REDIS_HOST}:6379
    host: ${REDIS_HOST}
    port: 6379
    ssl: false
    timeout: 5000

  servlet:
    multipart:
      max-file-size: 5MB  #单个文件最大大小
      max-request-size: 50MB #文件最多上传的大小

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /v3/api-docs

  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    # 隐藏路径映射Logging
    org.springframework.web.servlet: false

host:
  cors:
    whitelists:
      - http://localhost:8080
      - http://127.0.0.1:8080
      - http://localhost:5500
      - http://127.0.0.1:5500
      - http://jxy.me

wx:
  miniapp:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}
    msgDataFormat: JSON

security:
  jwt:
    secret: ${JWT_SECRET}

aliyun:
  oss:
    accessKeyId: ${ALIYUN_OSS_KEY_ID}
    accessKeySecret: ${ALIYUN_OSS_KEY_SECRET}
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: zq-teamup
  sms:
    accessKeyId: ${ALIYUN_SMS_KEY_ID}
    accessKeySecret: ${ALIYUN_SMS_KEY_SECRET}
    signName: 自强Studio
    templateCode:
      - name: verifyCode
        code: SMS_209826176

sentry:
  traces-sample-rate: 1.0
  send-default-pii: true

mq:
  rabbit:
    host: 42.193.50.174
    port: 5672
    virtualHost: /teamup
    username: teamup
    password: ${RABBITMQ_PASSWORD}

es:
  port: 9200
  hostname:  server
  alias: true  # 是否使用别名的方式访问

