server:
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /v3/api-docs

  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    # 隐藏路径映射Logging
    org.springframework.web.servlet: false

host:
  cors:
    whitelists:
      - http://localhost:8080
      - http://localhost:5500
      - http://jxy.me