# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Server CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  JOB_NAME: teamup-backend-test

  DOCKER_HOST: ccr.ccs.tencentyun.com
  DOCKER_NAMESPACE: ziqiang
  IMAGE_NAME: ${{ env.JOB_NAME }}

  WORKING_DIR: ~/${{ env.JOB_NAME }}
  DOCKER_COMPOSE_FILE: docker-compose-test.yml

  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SSH_HOST: ${{ secrets.TEST_SSH_HOST }}
  SSH_USERNAME: ${{ secrets.TEST_SSH_USERNAME }}
  SSH_PASSWORD: ${{ secrets.TEST_SSH_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ 'redis', 'spring' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Build Spring project
        run: |
          gradle buildDevJar


      - name: Using cache for docker
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: docker-layer-caching-${{ github.workflow }}-${{ matrix.image }}-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.workflow }}-${{ matrix.image }}-

      - name: build and push docker image ${{ matrix.image }}
        run: |
          docker login ${{ env.DOCKER_HOST }} --username=${{ env.DOCKER_USERNAME }} --password=${{ env.DOCKER_PASSWORD }}
          docker build -f docker/${{ matrix.image }}/Dockerfile -t ${{ env.DOCKER_HOST }}/${{ env.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ matrix.image }} .
          docker push ${{ env.DOCKER_HOST }}/${{ env.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ matrix.image }}
          docker image prune -f
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Turn down docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ env.SSH_PASSWORD }}
          script: |
            mkdir -p ${{ env.WORKING_DIR }}
            cd ${{ env.WORKING_DIR }}
            if [ -f docker-compose.yml ]; then
              docker login ${{ env.DOCKER_HOST }} --username=${{ env.DOCKER_USERNAME }} --password=${{ env.DOCKER_PASSWORD }}
              docker-compose pull
              docker-compose down
            fi

      - name: Update docker compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ env.SSH_PASSWORD }}
          source: ./docker/${{ env.DOCKER_COMPOSE_FILE }}
          target: ${{ env.WORKING_DIR }}

      - name: Rename docker compose file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ env.SSH_PASSWORD }}
          script: |
            cd ${{ env.WORKING_DIR }}
            mv ${{ env.DOCKER_COMPOSE_FILE }} docker-compose.yml

      - name: Restart docker compose containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ env.SSH_PASSWORD }}
          script: |
            cd ${{ env.WORKING_DIR }}
            docker login ${{ env.DOCKER_HOST }} --username=${{ env.DOCKER_USERNAME }} --password=${{ env.DOCKER_PASSWORD }}
            docker-compose pull
            docker-compose up -d --remove-orphans
            docker image prune -f